### ISSUE TITLE
Inconsistency in Total DFI burned

### ISSUE THREAD

**Issue by RomanShumkov** [DeFiCh/scan#1034]
#### What happened:
There are two counters of "Total DFI burned" on https://defiscan.live/ and they are indicating different amounts of DFI burned. See screenshot for details.

#### What you expected to happen:
I expected Total DFI burned counters to show the same amount regardless of where they are placed on the page.

#### How to reproduce it (as minimally and precisely as possible):
Visit https://defiscan.live/ and check two counters which are marked on the screenshot.

#### Anything else we need to know?:
<img width="1230" alt="Screenshot 2022-03-12 at 13 09 15" src="https://user-images.githubusercontent.com/548534/158015815-527b210d-ecf0-428b-88c0-87c1e7c71d9a.png">

**Comment by joeldavidw** [comment]
Hi @RomanShumkov thank you for reporting this issue. The team have identified the issue and will implementing a fix on [whale](https://github.com/DeFiCh/whale) which would fix this issue on Scan.

/triage accepted
/area store

**Comment by joeldavidw** [comment]
The fix has been implemented https://github.com/DeFiCh/whale/issues/845.
