### ISSUE TITLE
`Oracle` Implement Daily, Weekly, Monthly Graphs

### ISSUE THREAD

**Issue by joeldavidw** [DeFiCh/scan#1040]
What would you like to be added:
As part of UI/UX update for the oracles page. We would need the following:
- Implementation of Daily, Weekly, Monthly Graphs (Awaiting https://github.com/DeFiCh/whale/pull/836)

/triage accepted
/area ui-ux oracles

**Comment by nichellekoh** [comment]
Awaiting [#853](https://github.com/DeFiCh/whale/pull/853/files) instead
