### ISSUE TITLE
vault next Collateral Ratio uses DUSD with value 1 in collateral (should be 0.99)

### ISSUE THREAD

**Issue by kuegi** [DeFiCh/scan#1175]
According to the dfip, the DUSD value when used as collateral is 0.99
But for the calculation of "next collateral ratio", you use 1 in the case of DUSD. this leads to wrong "next" values.

error is in the combination of 
https://github.com/DeFiCh/scan/blob/ee92c15bd109189ad6da54f166cd2f948968c807/src/pages/vaults/utils/NextCollateralizationRatio.tsx#L32-L37

and

https://github.com/DeFiCh/scan/blob/ee92c15bd109189ad6da54f166cd2f948968c807/src/pages/vaults/utils/NextCollateralizationRatio.tsx#L6

**Comment by joeldavidw** [comment]
Thanks @kuegi for spotting this.

/triage accepted

**Comment by legorado** [comment]
Today I noticed, that the collateral value next to the token amount is exactly the same at DUSD. This should also be 0.99 of the token amount. For the calculation of "Total Collateral Value" it seems to be correct.
