### ISSUE TITLE
Vault next ratio is wrong

### ISSUE THREAD

**Issue by Krysh90** [DeFiCh/scan#1241]
#### What happened:
I am using RPC to get information about my vault. Since 2.8.1 there is the possibility to get next ratio. Today I saw that RPC information differs to defiscan displayed information of my vault. My vault consists of DFI, BTC, ETH and only has DUSD as loan. In my attached screenshot you can see that next prices of all 3 collaterals is lower than current.

![2022-06-12 07 47 36](https://user-images.githubusercontent.com/4957647/173217672-854ca63f-fe48-409d-be50-111d1caf031b.jpeg)

On defiscan my vault ratio is 163 and next collateral ratio is displayed as 164, which can't be true. 

<img width="386" alt="image" src="https://user-images.githubusercontent.com/4957647/173218020-09414770-1ae9-444a-88a9-2858e6111cea.png">

On RPC with verbose flag it reports 162.

<img width="196" alt="image" src="https://user-images.githubusercontent.com/4957647/173218158-309eb5df-699f-44f8-82ee-2a834da04286.png">

#### What you expected to happen:
That RPC information and defiscan information are ident and do not differ.

#### How to reproduce it (as minimally and precisely as possible):
On production environment it will be hard to reproduce as oracles are involved. Anyways how I would test it.
1. vault with DFI as collateral and DUSD as loan
2. next price of DFI oracle needs to be lower as current
3. next collateral ratio should be lower too

#### Anything else we need to know?:
Not that I am aware of. 

EDIT: added additional images for ratios from defiscan and RPC

**Comment by siradji** [comment]
Thank you @Krysh90 for openings this issue. We'll investigate and fix it as soon as possible.
