### ISSUE TITLE
Show PoolSwap/CompositeSwap outcome in Transaction page

### ISSUE THREAD

**Issue by fuxingloh** [DeFiCh/scan#1277]
#### What would you like to be added:

To add 1 more column below this and call it "ToAmount".
<img width="751" alt="image" src="https://user-images.githubusercontent.com/4266087/175316853-a0c39106-9dfc-4bf4-9ca8-1ae29b098c38.png">

We can use the account history API to get the outcome amount. 

https://github.com/JellyfishSDK/jellyfish/blob/1da85986399e670a06e4206fb70472c66db266b6/packages/whale-api-client/src/api/address.ts#L20-L22

```ts
  async getAccountHistory (address: string, height: number, txno: number): Promise<AddressHistory | undefined> {
    return await this.client.requestData('GET', `address/${address}/history/${height}/${txno}`)
  }
```

- address: string - to address, this information is available in DfTx
- height: number - block height of the transaction, this information is available in Transaction
- txno: number - transaction order in the block, this information is available in Transaction

#### Why is this needed:

For better UX, to show each transaction PoolSwap outcome.

**Comment by kyleleow** [comment]
@fuxingloh Can I suggest to rename the existing `Max Amount` label to `Max Price` to match with the property name, while adding `toAmount` with the label of `Amount`? 

E.g.:
<img width="1487" alt="image" src="https://user-images.githubusercontent.com/40191153/196900152-0fcae9d7-188a-4286-b83e-6b8e55e17646.png">

**Comment by fuxingloh** [comment]
> @fuxingloh Can I suggest to rename the existing `Max Amount` label to `Max Price` to match with the property name, while adding `toAmount` with the label of `Amount`?

Yup this works! 💋
