### ISSUE TITLE
add links to app store and playstore for `DeFiChain Wallet`

### ISSUE THREAD

**Issue by thedoublejay** [DeFiCh/scan#162]
#### What would you like to be added:
Would be nice to have some links on the explorer to app store and play store once it's ready.

**Comment by fuxingloh** [comment]
DeFi Scan should be wallet implementation agnostic. 

DeFi Scan provides a scan of the DeFi blockchain. It should not be concerned with the wallet as it can exist on its own without referencing any wallet ecosystem or patterns.
