### ISSUE TITLE
UI enhancements in Prices and Assets page

### ISSUE THREAD

**Issue by jtlntno-cake** [DeFiCh/scan#164]
#### What would you like to be added:
• Change the 'Tiigo' logo to improve consistency among other icons. 
• Add logos section to each individual asset page
• Rewording 'Inactive' to 'Closed'
• Revised icon for tooltip - make it less prominent to harmonize with text
• Changed color from 'yellow' to 'neutral gray' – makes it less alarming.

Designs and assets can be found here:
Price page: https://marvelapp.com/prototype/74de579/screen/80840940/handoff
Asset page: https://marvelapp.com/prototype/74de579/screen/80840939/handoff

#### Why is this needed:
Upon gathering feedbacks, there are visual improvements that are identified that can be added.

**Comment by siradji** [comment]
@jtlntno-cake, what yellow color are you referring to here?
