### ISSUE TITLE
Include Netlify Badge in Footer

### ISSUE THREAD

**Issue by jtlntno-cake** [DeFiCh/scan#255]
#### What would you like to be added:
Netlify requirement for backlinks. Netlify provided a badge for use. We can add this to the footer. 

I selected color-accent-badge from this [link](https://www.netlify.com/press/#badges)

![image](https://user-images.githubusercontent.com/85162376/132346521-b0652886-b4df-48e1-9c2d-cb8c70064965.png)

Code snippet from their website is also provided
`
  <a href="https://www.netlify.com">
    <img src="https://www.netlify.com/img/global/badges/netlify-color-accent.svg" alt="Deploys by Netlify" />
  </a>`

#### Why is this needed:
Netlify requirement for open-source project

**Comment by fuxingloh** [comment]
![image](https://user-images.githubusercontent.com/4266087/132353363-8d22fb42-4e1f-4b25-938f-9bda91944b3a.png)
 
I will use the light icon instead
