### ISSUE TITLE
Update `HeaderCountBar` text colours

### ISSUE THREAD

**Issue by joeldavidw** [DeFiCh/scan#505]
#### What would you like to be added:

To match the new UI design.

![image](https://user-images.githubusercontent.com/4586209/140505279-fdc07fdb-d91a-434c-bfcb-b98fd26d27ce.png)

Colors:

- Background: primary-700
- Title: primary-100
- Text: white (#FFFFFF)

/triage accepted
/area ui-ux

**Comment by RomanShumkov** [comment]
Just a friendly feedback: while the color of header is nice, it doesn't play well with loading indicator when switching between pages. Loading indicator is close to being invisible after this change and UI doesn't feel as responsive when navigating between pages - nothing is happening for a second or two and then new page is presented in a blink of an eye.

**Comment by siradji** [comment]
> Just a friendly feedback: while the color of header is nice, it doesn't play well with loading indicator when switching between pages. Loading indicator is close to being invisible after this change and UI doesn't feel as responsive when navigating between pages - nothing is happening for a second or two and then new page is presented in a blink of an eye.

@RomanShumkov thanks for the input. Will fix this soon.
