### ISSUE TITLE
Blocks and transaction on homepage should change color on hover

### ISSUE THREAD

**Issue by siradji** [DeFiCh/scan#506]
#### What would you like to be added:
Add primary color (text-primary-500) to blocks and transactions on homepage on hover.
#### Why is this needed:
Improvement request.

**Comment by siradji** [comment]
@joeldavidw @R15J

**Comment by joeldavidw** [comment]
@siradji Update on the hover states

background: primary 100 or 50 (See which matches the design better)
text: underline when hovered

![image](https://user-images.githubusercontent.com/4586209/139645767-f0561f18-9976-4d48-a090-326e28d42f0b.png)
