### ISSUE TITLE
Categorisation of assets on `Prices` page

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/scan#523]
#### To allow filtering by following categories (in this order):
- Stocks
- ETF
- Commodity
- Cryptocurrency
- Forex
- Others
- Available on DeFiChain (as a separate sub section)
    - Yes (Default selection; to hide tokens not listed on DeFiChain by default)
    - No

To include a 'View All' option that will select all filter options.
- In 'View All', prices will be displayed in the following order:
    - Stocks
        - Available on DeFiChain
        - Unavailable on DeFiChain
    - ETF
        - Available on DeFiChain
        - Unavailable on DeFiChain
    - Commodity
        - Available on DeFiChain
        - Unavailable on DeFiChain
    - Cryptocurrency
        - Available on DeFiChain
        - Unavailable on DeFiChain
    - Forex
        - Available on DeFiChain
        - Unavailable on DeFiChain
    - Others
        - Available on DeFiChain
        - Unavailable on DeFiChain

#### Default landing state: Show all prices except tokens unavailable on DeFiChain

Filters applied (and sorted in the following order):

✔️ Stocks
✔️ ETF
✔️ Commodity
✔️ Cryptocurrency
✔️ Foreign Exchange
✔️ Others
✔️ Available on DeFiChain: Yes

Reference: https://data.chain.link/ethereum/mainnet/crypto-usd

#### Why is this needed:

As the number of assets listed on DFC is rising, there's a need to simplify the display to ease cognitive load that comes with looking at a long list of unsorted assets.

**Comment by 0ptim** [comment]
Maybe it would be beneficial for the user to be able to filter for prices which are active and tradable on the DEX. The ticker-council will decide which assets will be tradable, and so the user might want to only see these relevant tickers.

Something else which came to mind was that maybe only the ticker symbols which are actually tradable should be displayed by default. This will assure, that new visitors of defiscan.live will not be misled by all the ticker prices, which they shortly after find out, can not be bought on the DEX.

That do you think?

**Comment by cyprus-karma** [comment]
+1

**Comment by 0ptim** [comment]
@ngyingzhong @joeldavidw I'm unsure by the lack of response.
Are this kind of inputs welcome, or is it more a distraction. Just let me know.

**Comment by cyprus-karma** [comment]
there is a mini-discussion on telegram about this. i think the suggestion is definitely useful.
https://t.me/defiblockchain_DE/125271

**Comment by ngyingzhong** [comment]
> Maybe it would be beneficial for the user to be able to filter for prices which are active and tradable on the DEX. The ticker-council will decide which assets will be tradable, and so the user might want to only see these relevant tickers.
> 
> Something else which came to mind was that maybe only the ticker symbols which are actually tradable should be displayed by default. This will assure, that new visitors of defiscan.live will not be misled by all the ticker prices, which they shortly after find out, can not be bought on the DEX.
> 
> That do you think?

Thanks for the great feedback @0ptim! Your inputs are definitely welcome. Resources have been prioritised to work on decentralised loans on DeFiChain, hence the delay in implementing this.

On top of categorising these tokens by type, I think it's also a great idea to filter the prices based on their status on the DEX. There have been other feedback from the community regarding this workstream which we are consolidating, and will push them into production as realistically soon as possible. Thanks again for your support, and please keep the feedback coming! Stay tuned 👀

**Comment by 0ptim** [comment]
Good to hear! Thanks for your reply 😊

**Comment by joeldavidw** [comment]
Thanks @0ptim & @cyprus-karma for your inputs!

/triage accepted
/area oracles

**Comment by joeldavidw** [comment]
@0ptim @cyprus-karma Filtering has been added! https://defiscan.live/oracles 😊
