### ISSUE TITLE
Bring back Token icons

### ISSUE THREAD

**Issue by 0ptim** [DeFiCh/scan#598]
#### What would you like to be added:
Icons for all kind of tokens should be implemented again.
Mentioned in PR #586, we don't have the rights to use these icons and other brokerage platforms don't display them.

Maybe I'm missing something here, but why is [Trading212](https://www.trading212.com/de/trading-instruments/invest) able to display all these icons?

#### Why is this needed:
UX will be improved and UI looks friendlier.

**Comment by ngyingzhong** [comment]
Thanks for the question @0ptim! We can't speak for other platforms but as you rightly pointed out, copyright is the main reason token icons are not displayed. That said, the team is working on a workaround to strike a balance between such technical issues and user experience.

**Comment by 0ptim** [comment]
Good to know. I think this kind of details can make a big difference for new users visiting the site. I hope there will be a way.
If you wish, I can try to get in contact with these platforms, to maybe get some more information about this.

**Comment by 0ptim** [comment]
Reporting back here.

Regarding our problem, I made [a post on the official Trading 212 community forum](https://community.trading212.com/t/company-icons-logos/52884). (I know that they are using these icons, because I'm actively using their App to manage my stock portfolio.)

According to the answers there, the usage of the logos on the T212 platform falls under the `fair-use-policy`.

I've found more information regarding this [here](https://www.nolo.com/legal-encyclopedia/when-you-need-permission-use-trademarks.html#:~:text=The%20short%20answer,and%20services%2C%20or) and [here](https://www.upcounsel.com/permission-to-use-logo#:~:text=a%20written%20agreement.-,Permission%20to%20Use%20Logo%20Agreement,to%20learn%20whether%20you%20should%20use%20a%20trademark%20or%20logo.,-However%2C%20the%20Publishing).

What do you guys think of this?
Is there any lawyer which you guys are in contact with?

I'll continue investigating in the meantime.

**Comment by ngyingzhong** [comment]
Hey @0ptim, awesome work and very insightful reply from Trading 212, thanks for researching 🙏   We understand that having the logos will improve user experience, thus we've had several discussions around this issue in the past week which we would like to share.

The key thing to clarify is the difference between Trading 212 (T212) and DeFiChain. While T212 is an online brokerage dealing with securities in the TradFi market, DeFiChain is a decentralized ecosystem providing DeFi services. In that regard, a user is able to access financial products that are offered in stock exchanges on T212, but he/she won't be able to do the same on DeFiChain. The Decentralized Loan feature on DFC, for example, provides access to loan tokens via decentralized tokenization which effectively allows users to mint loan tokens (e.g. dTSLA). The prices of these loan tokens (at the point of loan and payback) are [provided by oracles](https://defiscan.live/oracles), but beyond that has no relations with the public financial market. The value of these decentralized loan tokens are hence determined by the supply and demand on DeFiChain's DEX. As a result, it will be inaccurate to associate the the loan tokens with the actual world asset via the brand logos. 

That said, the platform seeks to place user experience at the forefront, and will continue to experiment to find a balance between usability and representation. Will provide an update the soonest possible!

**Comment by ngyingzhong** [comment]
Hi @0ptim, as a follow-up to our conversation, we have implemented the [new token design](https://defiscan.live/dex) on DeFi Scan and on the latest Light Wallet app release. Thanks for following along, I will be closing the issue for now 🥇
