### ISSUE TITLE
Clicking on footer links should retain query params after being redirected.

### ISSUE THREAD

**Issue by aikchun** [DeFiCh/scan#66]
#### What happened:
When clicking on the footer links, the page is redirection is done without preserving the `network` query params.

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/4145525/126596877-4c53e51a-e21a-4b81-9d20-730b60d1edb4.png">

If the routes in the footer were implemented, clicking on the links will redirect you without the query params.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/4145525/126597092-dc61cf0f-bf17-4749-83fc-4b98faf91595.png">

#### What you expected to happen:
When clicking on the page, the query params should be preserved, especially regarding the `network` param as it gives context to the network that the website is connected to.

Changing the `network` query param on the production site does change the network that the website is connected to. Thus indicating that the query param serves as the source of truth of the network connection.

**Comment by fuxingloh** [comment]
Thanks! I will explore
