### ISSUE TITLE
Incorrect global stats: Total running loans displayed instead of total active vault count

### ISSUE THREAD

**Issue by ngyingzhong** [DeFiCh/scan#668]
#### What happened:

"Total active vaults" on Scan displaying total running loans on DeFiChain, instead of total active vaults on DeFiChain

![image](https://user-images.githubusercontent.com/66629826/143821354-811c91d0-0e30-48a9-acb2-937d6f45f33a.png)

#### What you expected to happen:

To tally the total number of active vaults on DeFiChain

**Comment by siradji** [comment]
@ngyingzhong Should we move forward with Fuxing's suggestion?

**Comment by joeldavidw** [comment]
The stat shown is displaying the number of vaults with collaterals. Change `Total Active Vault` to `Collateralized Vaults` and add an info icon with the text `Total number of Ready and Active vaults`.

/triage accepted
/area vaults
