### ISSUE TITLE
Update all `token` symbols

### ISSUE THREAD

**Issue by joeldavidw** [DeFiCh/scan#800]
#### What would you like to be added:

To update the token symbols to make them 100% utilitarian and not resort to using brand colours and logos.

Required Features:

- Dynamic component similar to [`_Default` ](https://github.com/DeFiCh/scan/blob/main/src/components/icons/assets/tokens/_Default.tsx)
- Font Size based on the length of the text

<details>
<summary>Example Image</summary>

![telegram-cloud-photo-size-5-6244467288711474915-x](https://user-images.githubusercontent.com/4586209/148193502-8dff3cad-5906-4dbe-8af7-d5dae25690c2.jpg)

</details>

/triage accepted
/area ui-ux

**Comment by Hamzah46356000** [comment]
Hi

**Comment by Tyrkson** [comment]
Is the goal therefore to change all token icons to a circle with a black background and white text? 
And could you please assign me? I can't assign myself :(

**Comment by joeldavidw** [comment]
Hi @Tyrkson, Yep the goal is to update the icons to the circle with black background and white text. You can reference `src/components/icons/assets/tokens/_Default` to create a dynamic component all tokens.

**Comment by Tyrkson** [comment]
Okay I think I did it. Although I'm not sure if I did it the way you'd like it to be done, but I can't push my branch because I don't have a permission for that.
