### ISSUE TITLE
Flakey `cypress` tests

### ISSUE THREAD

**Issue by joeldavidw** [DeFiCh/scan#828]
#### What happened:
Multiple Cypress tests have been failing randomly with the error message: 

```
http://localhost:3000/?network=MainNet

The response we received from your web server was:

  > 500: Internal Server Error

This was considered a failure because the status code was not `2xx`.

If you do not want status codes to cause failures pass the option: `failOnStatusCode: false`

Because this error occurred during a `before all` hook we are skipping the remaining tests in the current suite: `<Header/> on iphone-x`

Although you have test retries enabled, we do not retry tests when `before all` or `after all` hooks fail
```

As `visit()` is in `before all` hook, cypress will not retry the test and skip all other tests in that block. `visit()` should be moved into `beforeEach` hook instead.

#### What you expected to happen:

Tests should be re-tried

**Comment by Tyrkson** [comment]
@joeldavidw Can you assign me please?

Thank you

**Comment by joeldavidw** [comment]
Hi @Tyrkson, the issue has not be triaged yet as we are still finding the root cause of this issue. Will let you know once the issue has been confirmed. Thanks!
