### ISSUE TITLE
Search Result Area – Hide By Click

### ISSUE THREAD

**Issue by 0ptim** [DeFiCh/scan#845]
#### What happened:
The search result area hides after two clicks.

#### What you expected to happen:
The search result area hides after one click.

#### How to reproduce it (as minimally and precisely as possible):
![DeFiScan_searchbar_visibility](https://user-images.githubusercontent.com/25133399/149914832-01153af9-b11d-4476-a113-1848845936e3.gif)

**Comment by joeldavidw** [comment]
Hi @0ptim, thank you for reporting! We have looked into the issue. The fix for this issue will be added during the rebuild of the search bar alongside the release of the new Search API.

**Comment by siradji** [comment]
@joeldavidw how are we getting on this? It will also be good to make search modal closable by pressing the esc key
