### ISSUE TITLE
More Information on the "Vault - In Liquidation" Page. 

### ISSUE THREAD

**Issue by defidone** [DeFiCh/scan#892]
#### What would you like to be added:
A small note on the Vault page if an auction was bid on.

#### Why is this needed:

It's hard to keep track when you have a large vault in liquidation.

Currently you have to open each badge to see if someone has bid.

If you can see if a badge has been bid on on the first page, you can open it directly for more details.

**Comment by joeldavidw** [comment]
Hi @defidone, thank you for the feedback! We will add this in the next auctions page update.
