### ISSUE TITLE
Add a will be liquidated warning to the vault detail page for keyword monitors

### ISSUE THREAD

**Issue by mmhpt** [DeFiCh/scan#904]
#### What would you like to be added:
I suggest to add a warning like "vault will be liquidated" to the detail page of a vault, if the next ratio will be smaller than the minimum ratio
#### Why is this needed:
Keyword monitors like https://uptimerobot.com/ can scan the detail page of the vault for this warning and will send an alarm (like an automated call) to the owner of the vault

**Comment by joeldavidw** [comment]
@mmhpt thank you for the feedback! The team will work on integrating this in the vaults page.

/triage accepted
/area ui-ux vaults
/needs design

**Comment by joeldavidw** [comment]
@mmhpt Thanks again for this feature request and sorry for the delay. This feature has been added and keyword that should be used for the monitors is "Vault may go into liquidation".

Warning & Keywords are added when the vault's Next Collateralization Ratio is lesser than 1.1x of it's Min. Collateralization Ratio.
